spring:
  application:
    name: hsu-festival-2025
  config:
    import: optional:application-secret.yml

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# openai key
openai:
  key: ${OPENAI_API_KEY}