name: hsu-festival
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hsu-festival:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/hsu-festival:latest

      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/hsu-festival:latest
            sudo docker stop hsu-festival || true
            sudo docker rm hsu-festival || true
            sudo docker run -d \
              --name hsu-festival \
              --restart always \
              --log-driver=syslog \
              -p 8080:8080 \
              -e TZ=Asia/Seoul \
              -e SPRING_PROFILES_ACTIVE=dev \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
              -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -e S3_BUCKET=${{ secrets.S3_BUCKET }} \
              -e S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }} \
              -e S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }} \
              ${{ secrets.DOCKER_USERNAME }}/hsu-festival:latest
            sudo docker image prune -a -f

      - name: Check logs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            if sudo docker ps -a --format '{{.Names}}' | grep -q '^hsu-festival$'; then
              sudo docker logs hsu-festival
            else
              echo "!!! no container !!!"
              exit 1
            fi
